In [181]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [182]:
original_data = pd.read_csv('data_processed.csv')

In [183]:
data = original_data.copy()

In [184]:
data

name                 type  \
0   MacLehose Trail (Section 1) Pak Tam Chung to L...  Long-distance Trail   
1   MacLehose Trail (Section 2) Long Ke to Pak Tam Au  Long-distance Trail   
2   MacLehose Trail (Section 3) Pak Tam Au to Kei ...  Long-distance Trail   
3   MacLehose Trail (Section 4) Kei Ling Ha to Tat...  Long-distance Trail   
4   MacLehose Trail (Section 5) Tate's Cairn to Ta...  Long-distance Trail   
..                                                ...                  ...   
84  Hong Kong Trail (Section 6) Mount Parker Road ...     Hon g Kong Trail   
85                            MacLehose Trail overall  Long-distance Trail   
86                            Hong Kong Trail overall  Long-distance Trail   
87                               Lantau Trail overall  Long-distance Trail   
88                               Wilson Trail overall  Long-distance Trail   

     length_km  duration_hour difficulty                              region  \
0    10.600000       3.000000       Hard                            Sai Kung   
1    13.500000       5.000000       Hard                            Sai Kung   
2    10.200000       4.000000       Hard                            Sai Kung   
3    12.700000       5.000000       Hard                            Sai Kung   
4    10.600000       4.500000       Hard             Central New Territories   
..         ...            ...        ...                                 ...   
84    9.242632       2.385429   Moderate                    Hong Kong Island   
85  100.000000       2.385429       Hard                     New Territories   
86   50.000000       2.385429   Moderate                    Hong Kong Island   
87   70.000000       2.385429   Moderate                              Lantau   
88   78.000000       2.385429       Hard  Hong Kong Island / New Territories   

                                         type_of_view    rating  \
0                                         beach, lake  4.500000   
1   beauty of the coast of Hong Kong, Sai Wan beac...  4.700000   
2                                      forests, views  4.500000   
3                                  views, wildflowers  4.500000   
4                                   forests and views  4.500000   
..                                                ...       ...   
84                                  Tai Tam Reservoir  4.400000   
85                                 beaches, mountains  4.300000   
86                      Views and tourist attractions  4.600000   
87  mountain peaks, traditional villages, coastal ...  4.400000   
88  Tai Tam, Quarry Bay, Ma On Shan, Lion Rock, Ka...  4.270769   

    elevation_gain  
0           1250.0  
1           2168.0  
2           1994.0  
3           2805.0  
4           1791.0  
..             ...  
84           180.0  
85         16571.0  
86          5524.0  
87         10036.0  
88         17740.0  

[89 rows x 9 columns]

In [185]:
print(data['type'].unique())

['Long-distance Trail' 'Hong Kong Trail' 'Lantau Trail' 'Wilson Trail'
 'Country Trail' 'Nature Trail' 'Tree Walk' 'Family Walk' 'Geo Route'
 'Recommended Route' 'Hon g Kong Trail']


In [186]:
data['type'].value_counts()

type
Country Trail          21
Long-distance Trail    14
Recommended Route      10
Hong Kong Trail         8
Nature Trail            7
Wilson Trail            7
Lantau Trail            6
Tree Walk               6
Family Walk             5
Geo Route               4
Hon g Kong Trail        1
Name: count, dtype: int64

In [187]:
data['type'] = data['type'].replace('Hon g Kong Trail','Hong Kong Trail' )

In [188]:
#There is only one data point of group 3?
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
type = data['type']
type_encoded = encoder.fit_transform(type)
type_encoded

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
       4, 9, 9, 9, 9, 9, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 6, 6, 6, 6, 6, 6, 6, 8, 8, 8, 1, 1, 1, 1, 2, 2, 2, 2, 7, 7,
       7, 7, 0, 0, 0, 0, 7, 3, 7, 1, 8, 8, 8, 0, 7, 7, 7, 7, 3, 5, 5, 5,
       5])

In [189]:
encoder.classes_

array(['Country Trail', 'Family Walk', 'Geo Route', 'Hong Kong Trail',
       'Lantau Trail', 'Long-distance Trail', 'Nature Trail',
       'Recommended Route', 'Tree Walk', 'Wilson Trail'], dtype=object)

In [190]:
data

name                 type  \
0   MacLehose Trail (Section 1) Pak Tam Chung to L...  Long-distance Trail   
1   MacLehose Trail (Section 2) Long Ke to Pak Tam Au  Long-distance Trail   
2   MacLehose Trail (Section 3) Pak Tam Au to Kei ...  Long-distance Trail   
3   MacLehose Trail (Section 4) Kei Ling Ha to Tat...  Long-distance Trail   
4   MacLehose Trail (Section 5) Tate's Cairn to Ta...  Long-distance Trail   
..                                                ...                  ...   
84  Hong Kong Trail (Section 6) Mount Parker Road ...      Hong Kong Trail   
85                            MacLehose Trail overall  Long-distance Trail   
86                            Hong Kong Trail overall  Long-distance Trail   
87                               Lantau Trail overall  Long-distance Trail   
88                               Wilson Trail overall  Long-distance Trail   

     length_km  duration_hour difficulty                              region  \
0    10.600000       3.000000       Hard                            Sai Kung   
1    13.500000       5.000000       Hard                            Sai Kung   
2    10.200000       4.000000       Hard                            Sai Kung   
3    12.700000       5.000000       Hard                            Sai Kung   
4    10.600000       4.500000       Hard             Central New Territories   
..         ...            ...        ...                                 ...   
84    9.242632       2.385429   Moderate                    Hong Kong Island   
85  100.000000       2.385429       Hard                     New Territories   
86   50.000000       2.385429   Moderate                    Hong Kong Island   
87   70.000000       2.385429   Moderate                              Lantau   
88   78.000000       2.385429       Hard  Hong Kong Island / New Territories   

                                         type_of_view    rating  \
0                                         beach, lake  4.500000   
1   beauty of the coast of Hong Kong, Sai Wan beac...  4.700000   
2                                      forests, views  4.500000   
3                                  views, wildflowers  4.500000   
4                                   forests and views  4.500000   
..                                                ...       ...   
84                                  Tai Tam Reservoir  4.400000   
85                                 beaches, mountains  4.300000   
86                      Views and tourist attractions  4.600000   
87  mountain peaks, traditional villages, coastal ...  4.400000   
88  Tai Tam, Quarry Bay, Ma On Shan, Lion Rock, Ka...  4.270769   

    elevation_gain  
0           1250.0  
1           2168.0  
2           1994.0  
3           2805.0  
4           1791.0  
..             ...  
84           180.0  
85         16571.0  
86          5524.0  
87         10036.0  
88         17740.0  

[89 rows x 9 columns]

In [191]:
print(encoder.classes_)

['Country Trail' 'Family Walk' 'Geo Route' 'Hong Kong Trail'
 'Lantau Trail' 'Long-distance Trail' 'Nature Trail' 'Recommended Route'
 'Tree Walk' 'Wilson Trail']


In [192]:
from sklearn.preprocessing import LabelBinarizer
encoder_1hot = LabelBinarizer()
type_1hot = encoder_1hot.fit_transform(type)
type_1hot
# Change to one-hot type

array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0,

In [193]:
print(data['difficulty'].unique())

['Hard' 'Moderate' 'Easy']


In [200]:
data['difficulty'].value_counts()

difficulty
Hard        44
Easy        23
Moderate    22
Name: count, dtype: int64

In [194]:
from sklearn.preprocessing import OrdinalEncoder
categories = [['Easy', 'Moderate', 'Hard']] #why do [[]]?
encoder_ordinal = OrdinalEncoder(categories=categories)
difficulty = data[['difficulty']] #what tf the array shape here??
difficulty_encoded = encoder_ordinal.fit_transform(difficulty)
difficulty_encoded



array([[2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [2.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [2.],
       [0.],
       [2.],
       [2.],
       [2.],
       [1.],
       [1.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [1.],
       [2.],
       [2.],
       [2.],
       [0.],
       [1.],
       [2.],
       [2.],
       [2.],
       [1.],
       [2.],
       [2.],
       [2.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [2.],
       [0.],
       [2.],
       [2.],
       [1.],
       [2.],
       [2.],
       [2.],
       [2.],
       [1.],
       [0.],
       [0.],

In [201]:
print(data['region'].unique())

['Sai Kung' 'Central New Territories' 'West New Territories'
 'Hong Kong Island' 'Lantau' 'North New Territories' 'New Territories'
 'Hong Kong Island / New Territories']


In [ ]:
data['region'].value_counts()
# Gộp -> others ==2?

region
Sai Kung                              19
Hong Kong Island                      18
Central New Territories               15
Lantau                                15
West New Territories                  12
North New Territories                  8
New Territories                        1
Hong Kong Island / New Territories     1
Name: count, dtype: int64

In [195]:
region = data[['region']] # Same tatics again??
region_1hot = encoder_1hot.fit_transform(region)
region_1hot


array([[0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0,

In [196]:
encoder_1hot.classes_

array(['Central New Territories', 'Hong Kong Island',
       'Hong Kong Island / New Territories', 'Lantau', 'New Territories',
       'North New Territories', 'Sai Kung', 'West New Territories'],
      dtype='<U34')

In [197]:
print(region_1hot.__class__)

<class 'numpy.ndarray'>


In [198]:
print(difficulty_encoded.__class__)

<class 'numpy.ndarray'>


In [199]:

'''
label/one-hot?/binary for categorical features
Test TF-IDF, BoW, and Word embeddings for type_of_view, evaluate with K-means using Silhouette Score, select TF-IDF if best.
Process type, region (one-hot encoding), difficulty (Label Encoding), normalize with StandardScaler.
Use best type to test K-means, DBSCAN, GMM, Hierarchical Clustering; compare Silhouette Scores + interpretability <=> comparable table? -> explain
Visualize best clusters with scatter plot (PCA) and word cloud.
Document: Describe experiments, comparison table, explain cluster meanings (trail recommendations).'''

'\nlabel/one-hot?/binary for categorical features\nTest TF-IDF, BoW, and Word embeddings for type_of_view, evaluate with K-means using Silhouette Score, select TF-IDF if best.\nProcess type, region (one-hot encoding), difficulty (Label Encoding), normalize with StandardScaler.\nUse best type to test K-means, DBSCAN, GMM, Hierarchical Clustering; compare Silhouette Scores + interpretability <=> comparable table? -> explain\nVisualize best clusters with scatter plot (PCA) and word cloud.\nDocument: Describe experiments, comparison table, explain cluster meanings (trail recommendations).'